alias gst='git status -sb --ignore-submodules=all'
alias gx='gitx --all .'
alias gl='git pull --rebase --recurse-submodules'
alias gp='git gc;git push'
alias gd='git difftool -w'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gb='git branch'
alias gba='git branch -a'
alias gg='git lol'
alias gsu='git submodule update --recursive'
alias grh='git reset HEAD'
alias gdss='git diff --shortstat'
alias gitn='git --noop'
alias st='stree'
alias st.='stree .'
