alias gst='c;git status'
alias gx='gitx --all .'
alias gl='git pull'
alias gp='git gc;git push'
alias gd='git diff |mate'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gb='git branch'
alias gba='git branch -a'
alias gg='git log --graph --pretty=oneline --abbrev-commit'
alias grh='git reset HEAD'
alias gdss='git diff --shortstat'
