alias ll='/bin/ls -AflGph'
alias m.="mate ."
alias m="mate"
alias s.="subl ."
alias s="subl"
alias flush='dscacheutil -flushcache'
alias scratch="cd ~/Documents/Scratch"
alias work="cd ~/Work "
alias git=hub
alias ..="cd ../"
alias ...="cd ../../"
alias cfw="coffee -c -b -l -w ."