alias dl="tail -f log/development.log"
alias r="rake"
alias rr="clear; rake routes"
alias rs="r stats"
alias gu='sudo gem uninstall'
alias cw='compass watch'
alias be='clear; bundle exec'
alias bi='clear; bundle install'
alias bu='clear; bundle install'
alias bss='be script/rails s'
alias bsc='be script/rails c'
